import type { ProviderModelConfig } from "@earendil-works/pi-coding-agent";

/**
 * Hardcoded snapshot of chat models from the LLM Gateway /v1/models API.
 * Used as a zero-latency seed so models are registered before the live
 * fetch on session_start completes. Run `bun run test` to validate this
 * snapshot against the live API and detect drift.
 *
 * Snapshot generated: 2026-06-23
 * Model count: 182
 */
export const LLMGATEWAY_STATIC_MODELS: ProviderModelConfig[] = [
  {
    id: "auto",
    name: "Auto Route",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 131072,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.15,
      output: 0.6,
      cacheRead: 0.075,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "gpt-4o-search-preview",
    name: "GPT-4o Search Preview",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 2.5,
      output: 10,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "gpt-4o-mini-search-preview",
    name: "GPT-4o Mini Search Preview",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.15,
      output: 0.6,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "gpt-4",
    name: "GPT-4",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 30,
      output: 60,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 8192,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "gpt-4o",
    name: "GPT-4o",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 2.5,
      output: 10,
      cacheRead: 1.25,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "gpt-3.5-turbo",
    name: "GPT-3.5 Turbo",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.5,
      output: 1.5,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 16385,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "gpt-4-turbo",
    name: "GPT-4 Turbo",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 10,
      output: 30,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "gpt-4.1",
    name: "GPT-4.1",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 2,
      output: 8,
      cacheRead: 0.5,
      cacheWrite: 0,
    },
    contextWindow: 1000000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "o1",
    name: "o1",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 15,
      output: 60,
      cacheRead: 7.5,
      cacheWrite: 0,
    },
    contextWindow: 200000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gpt-4.1-mini",
    name: "GPT-4.1 Mini",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.39999999999999997,
      output: 1.5999999999999999,
      cacheRead: 0.09999999999999999,
      cacheWrite: 0,
    },
    contextWindow: 1000000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "gpt-4.1-nano",
    name: "GPT-4.1 Nano",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.09999999999999999,
      output: 0.39999999999999997,
      cacheRead: 0.024999999999999998,
      cacheWrite: 0,
    },
    contextWindow: 1000000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "o3-mini",
    name: "o3 Mini",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 1.1,
      output: 4.4,
      cacheRead: 0.55,
      cacheWrite: 0,
    },
    contextWindow: 200000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "o4-mini",
    name: "o4 Mini",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 1.1,
      output: 4.4,
      cacheRead: 0.275,
      cacheWrite: 0,
    },
    contextWindow: 200000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gpt-oss-120b",
    name: "GPT OSS 120B",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.15,
      output: 0.75,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 131072,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gpt-oss-20b",
    name: "GPT OSS 20B",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.09999999999999999,
      output: 0.5,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 131072,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gpt-5-chat-latest",
    name: "GPT-5 Chat Latest",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 1.25,
      output: 10,
      cacheRead: 0.125,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "gpt-5.1",
    name: "GPT-5.1",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 1.25,
      output: 10,
      cacheRead: 0.125,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gpt-5.1-codex",
    name: "GPT-5.1 Codex",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 1.25,
      output: 10,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gpt-5.1-codex-mini",
    name: "GPT-5.1 Codex mini",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.25,
      output: 2,
      cacheRead: 0.024999999999999998,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gpt-5.2",
    name: "GPT-5.2",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 1.75,
      output: 14,
      cacheRead: 0.175,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gpt-5.2-pro",
    name: "GPT-5.2 Pro",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 21,
      output: 168,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gpt-5.4",
    name: "GPT-5.4",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 2.5,
      output: 15,
      cacheRead: 0.25,
      cacheWrite: 0,
    },
    contextWindow: 1050000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gpt-5.4-pro",
    name: "GPT-5.4 Pro",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 30,
      output: 180,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 1050000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gpt-5.4-mini",
    name: "GPT-5.4 Mini",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.75,
      output: 4.5,
      cacheRead: 0.075,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gpt-5.4-nano",
    name: "GPT-5.4 Nano",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.19999999999999998,
      output: 1.25,
      cacheRead: 0.02,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gpt-5.5",
    name: "GPT-5.5",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 5,
      output: 30,
      cacheRead: 0.5,
      cacheWrite: 0,
    },
    contextWindow: 1050000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gpt-5.5-pro",
    name: "GPT-5.5 Pro",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 30,
      output: 180,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 1050000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gpt-5.2-codex",
    name: "GPT-5.2 Codex",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 1.75,
      output: 14,
      cacheRead: 0.175,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gpt-5.3-codex",
    name: "GPT-5.3 Codex",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 1.75,
      output: 14,
      cacheRead: 0.175,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "claude-3-7-sonnet",
    name: "Claude 3.7 Sonnet",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 3,
      output: 15,
      cacheRead: 0.3,
      cacheWrite: 3.75,
    },
    contextWindow: 200000,
    maxTokens: 32000,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "claude-3-7-sonnet-20250219",
    name: "Claude 3.7 Sonnet (2025-02-19)",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 3,
      output: 15,
      cacheRead: 0.3,
      cacheWrite: 3.75,
    },
    contextWindow: 200000,
    maxTokens: 32000,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "claude-sonnet-4-5",
    name: "Claude Sonnet 4.5",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 3,
      output: 15,
      cacheRead: 0.3,
      cacheWrite: 3.75,
    },
    contextWindow: 200000,
    maxTokens: 32000,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "claude-sonnet-4-5-20250929",
    name: "Claude Sonnet 4.5 (2025-09-29)",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 3,
      output: 15,
      cacheRead: 0.3,
      cacheWrite: 3.75,
    },
    contextWindow: 200000,
    maxTokens: 32000,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 3,
      output: 15,
      cacheRead: 0.3,
      cacheWrite: 3.75,
    },
    contextWindow: 1000000,
    maxTokens: 32000,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 1,
      output: 5,
      cacheRead: 0.09999999999999999,
      cacheWrite: 1.25,
    },
    contextWindow: 200000,
    maxTokens: 32000,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "claude-haiku-4-5-20251001",
    name: "Claude Haiku 4.5 (2025-10-01)",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 1,
      output: 5,
      cacheRead: 0.09999999999999999,
      cacheWrite: 1.25,
    },
    contextWindow: 200000,
    maxTokens: 32000,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "claude-opus-4-1-20250805",
    name: "Claude Opus 4.1",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 15,
      output: 75,
      cacheRead: 1.5,
      cacheWrite: 18.75,
    },
    contextWindow: 200000,
    maxTokens: 32000,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "claude-3-opus",
    name: "Claude 3 Opus",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 15,
      output: 75,
      cacheRead: 1.5,
      cacheWrite: 18.75,
    },
    contextWindow: 200000,
    maxTokens: 32000,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "claude-opus-4-5-20251101",
    name: "Claude Opus 4.5",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 5,
      output: 25,
      cacheRead: 0.5,
      cacheWrite: 6.25,
    },
    contextWindow: 200000,
    maxTokens: 32000,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "claude-opus-4-6",
    name: "Claude Opus 4.6",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 5,
      output: 25,
      cacheRead: 0.5,
      cacheWrite: 6.25,
    },
    contextWindow: 1000000,
    maxTokens: 32000,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "claude-opus-4-7",
    name: "Claude Opus 4.7",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 5,
      output: 25,
      cacheRead: 0.5,
      cacheWrite: 6.25,
    },
    contextWindow: 1000000,
    maxTokens: 32000,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "claude-opus-4-8",
    name: "Claude Opus 4.8",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 5,
      output: 25,
      cacheRead: 0.5,
      cacheWrite: 6.25,
    },
    contextWindow: 1000000,
    maxTokens: 32000,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 1.25,
      output: 10,
      cacheRead: 0.125,
      cacheWrite: 0,
    },
    contextWindow: 1048576,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.3,
      output: 2.5,
      cacheRead: 0.03,
      cacheWrite: 0,
    },
    contextWindow: 1048576,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash Lite",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.09999999999999999,
      output: 0.39999999999999997,
      cacheRead: 0.01,
      cacheWrite: 0,
    },
    contextWindow: 1048576,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "gemini-pro-latest",
    name: "Gemini Pro Latest",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 2,
      output: 12,
      cacheRead: 0.19999999999999998,
      cacheWrite: 0,
    },
    contextWindow: 1048576,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro (Preview)",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 2,
      output: 12,
      cacheRead: 0.19999999999999998,
      cacheWrite: 0,
    },
    contextWindow: 1048576,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gemini-3.1-flash-lite",
    name: "Gemini 3.1 Flash Lite",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.25,
      output: 1.5,
      cacheRead: 0.024999999999999998,
      cacheWrite: 0.08333,
    },
    contextWindow: 1048576,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gemini-3.5-flash",
    name: "Gemini 3.5 Flash",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 1.5,
      output: 9,
      cacheRead: 0.15,
      cacheWrite: 0.08333,
    },
    contextWindow: 1048576,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gemini-3.1-flash-image-preview",
    name: "Gemini 3.1 Flash Image (Preview)",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.25,
      output: 1.5,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 65536,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "gemini-3-flash-preview",
    name: "Gemini 3 Flash (Preview)",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.5,
      output: 3,
      cacheRead: 0.049999999999999996,
      cacheWrite: 0,
    },
    contextWindow: 1048576,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gemini-2.5-flash-image",
    name: "Gemini 2.5 Flash Image",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.3,
      output: 30,
      cacheRead: 0.03,
      cacheWrite: 0,
    },
    contextWindow: 32768,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "gemini-3-pro-image-preview",
    name: "Gemini 3 Pro Image (Preview)",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 2,
      output: 12,
      cacheRead: 0.19999999999999998,
      cacheWrite: 0,
    },
    contextWindow: 65536,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "gemma-4-31b-it",
    name: "Gemma 4 31B IT",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.13,
      output: 0.38,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "gemma-4-26b-a4b-it",
    name: "Gemma 4 26B A4B IT",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.07,
      output: 0.33999999999999997,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "sonar-reasoning-pro",
    name: "Sonar Reasoning Pro",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 2,
      output: 8,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "sonar-pro",
    name: "Sonar Pro",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 3,
      output: 15,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 200000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "sonar",
    name: "Sonar",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 1,
      output: 1,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 130000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "grok-4",
    name: "Grok 4",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 3,
      output: 15,
      cacheRead: 0.75,
      cacheWrite: 0,
    },
    contextWindow: 256000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "grok-4-1-fast-reasoning",
    name: "Grok 4.1 Fast Reasoning",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.19999999999999998,
      output: 0.5,
      cacheRead: 0.049999999999999996,
      cacheWrite: 0,
    },
    contextWindow: 2000000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "grok-4-1-fast-non-reasoning",
    name: "Grok 4.1 Fast Non-Reasoning",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.19999999999999998,
      output: 0.5,
      cacheRead: 0.049999999999999996,
      cacheWrite: 0,
    },
    contextWindow: 2000000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "grok-4-20-beta-0309-reasoning",
    name: "Grok 4.20 Beta Reasoning (0309)",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 2,
      output: 6,
      cacheRead: 0.19999999999999998,
      cacheWrite: 0,
    },
    contextWindow: 2000000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "grok-4-20-beta-0309-non-reasoning",
    name: "Grok 4.20 Beta Non-Reasoning (0309)",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 2,
      output: 6,
      cacheRead: 0.19999999999999998,
      cacheWrite: 0,
    },
    contextWindow: 2000000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "grok-4-20-reasoning",
    name: "Grok 4.20 Reasoning",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 2,
      output: 6,
      cacheRead: 0.19999999999999998,
      cacheWrite: 0,
    },
    contextWindow: 2000000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "grok-4-20-non-reasoning",
    name: "Grok 4.20 Non-Reasoning",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 2,
      output: 6,
      cacheRead: 0.19999999999999998,
      cacheWrite: 0,
    },
    contextWindow: 2000000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "grok-4-3",
    name: "Grok 4.3",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 1.25,
      output: 2.5,
      cacheRead: 0.3125,
      cacheWrite: 0,
    },
    contextWindow: 1000000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "grok-build-0-1",
    name: "Grok Build 0.1",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 1,
      output: 2,
      cacheRead: 0.19999999999999998,
      cacheWrite: 0,
    },
    contextWindow: 256000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "mimo-v2.5-pro",
    name: "MiMo V2.5 Pro",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.435,
      output: 0.87,
      cacheRead: 0.0036,
      cacheWrite: 0,
    },
    contextWindow: 1000000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "mimo-v2-pro",
    name: "MiMo V2 Pro",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 1,
      output: 3,
      cacheRead: 0.19999999999999998,
      cacheWrite: 0,
    },
    contextWindow: 1000000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "mimo-v2.5",
    name: "MiMo V2.5",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.14,
      output: 0.28,
      cacheRead: 0.0028,
      cacheWrite: 0,
    },
    contextWindow: 1000000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "mimo-v2-omni",
    name: "MiMo V2 Omni",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.39999999999999997,
      output: 2,
      cacheRead: 0.08,
      cacheWrite: 0,
    },
    contextWindow: 256000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "llama-3.1-70b-instruct",
    name: "Llama 3.1 70B Instruct",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.72,
      output: 0.72,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 8192,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "llama-3.2-11b-instruct",
    name: "Llama 3.2 11B Instruct",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.07,
      output: 0.33,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 8192,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "llama-3.1-nemotron-ultra-253b",
    name: "Llama 3.1 Nemotron Ultra 253B",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.6,
      output: 1.7999999999999998,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 8192,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "llama-3.3-70b-instruct",
    name: "Llama 3.3 70B Instruct",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.13,
      output: 0.39999999999999997,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 131072,
    maxTokens: 8192,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "llama-4-scout-17b-instruct",
    name: "Llama 4 Scout 17B Instruct",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.16999999999999998,
      output: 0.66,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 131072,
    maxTokens: 8192,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "llama-4-maverick-17b-instruct",
    name: "Llama 4 Maverick 17B Instruct",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.24,
      output: 0.9700000000000001,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 1048576,
    maxTokens: 8192,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "llama-3-8b-instruct",
    name: "Llama 3 8B Instruct",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.04,
      output: 0.04,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 8192,
    maxTokens: 8192,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "llama-3-70b-instruct",
    name: "Llama 3 70B Instruct",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.51,
      output: 0.74,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 8192,
    maxTokens: 8192,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "llama-3.2-3b-instruct",
    name: "Llama 3.2 3B Instruct",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.03,
      output: 0.049999999999999996,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 32768,
    maxTokens: 8192,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "deepseek-v3.1",
    name: "DeepSeek V3.1",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.56,
      output: 1.68,
      cacheRead: 0.112,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "deepseek-v3.2",
    name: "DeepSeek V3.2",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.28,
      output: 0.42,
      cacheRead: 0.028,
      cacheWrite: 0,
    },
    contextWindow: 163840,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.435,
      output: 0.87,
      cacheRead: 0.003625,
      cacheWrite: 0,
    },
    contextWindow: 1050000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.14,
      output: 0.28,
      cacheRead: 0.0028,
      cacheWrite: 0,
    },
    contextWindow: 1050000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "mistral-large-latest",
    name: "Mistral Large Latest",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 4,
      output: 12,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "pixtral-large-latest",
    name: "Pixtral Large Latest",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 4,
      output: 12,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "mistral-large-2512",
    name: "Mistral Large 3",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.5,
      output: 1.5,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "mistral-small-2506",
    name: "Mistral Small 3.2",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.09999999999999999,
      output: 0.3,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "ministral-14b-2512",
    name: "Ministral 14B",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.19999999999999998,
      output: 0.19999999999999998,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "ministral-8b-2512",
    name: "Ministral 8B",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.15,
      output: 0.15,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "ministral-3b-2512",
    name: "Ministral 3B",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.09999999999999999,
      output: 0.09999999999999999,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 131072,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "codestral-2508",
    name: "Codestral",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.3,
      output: 0.8999999999999999,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 256000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "devstral-2512",
    name: "Devstral 2",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.39999999999999997,
      output: 2,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "devstral-small-2507",
    name: "Devstral Small 1.1",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.09999999999999999,
      output: 0.3,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 131072,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "minimax-m3",
    name: "MiniMax M3",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.6,
      output: 2.4,
      cacheRead: 0.12,
      cacheWrite: 0,
    },
    contextWindow: 512000,
    maxTokens: 40960,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "minimax-m2.7",
    name: "MiniMax M2.7",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.3,
      output: 1.2,
      cacheRead: 0.06,
      cacheWrite: 0,
    },
    contextWindow: 204800,
    maxTokens: 40960,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "minimax-m2.7-highspeed",
    name: "MiniMax M2.7 Highspeed",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.6,
      output: 2.4,
      cacheRead: 0.06,
      cacheWrite: 0,
    },
    contextWindow: 204800,
    maxTokens: 40960,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "minimax-m2.5",
    name: "MiniMax M2.5",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.3,
      output: 1.2,
      cacheRead: 0.03,
      cacheWrite: 0,
    },
    contextWindow: 228700,
    maxTokens: 40960,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "minimax-m2.5-highspeed",
    name: "MiniMax M2.5 Highspeed",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.6,
      output: 2.4,
      cacheRead: 0.03,
      cacheWrite: 0,
    },
    contextWindow: 204800,
    maxTokens: 40960,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "minimax-m2",
    name: "MiniMax M2",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.19999999999999998,
      output: 1,
      cacheRead: 0.03,
      cacheWrite: 0,
    },
    contextWindow: 196608,
    maxTokens: 40960,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "minimax-m2.1",
    name: "MiniMax M2.1",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.27,
      output: 1.1,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 204800,
    maxTokens: 40960,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "minimax-m2.1-lightning",
    name: "MiniMax M2.1 Lightning",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.12,
      output: 0.48,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 196608,
    maxTokens: 40960,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "minimax-text-01",
    name: "MiniMax Text 01",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.19999999999999998,
      output: 1.1,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 1000000,
    maxTokens: 40960,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "kimi-k2",
    name: "Kimi K2",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 1,
      output: 3,
      cacheRead: 0.5,
      cacheWrite: 0,
    },
    contextWindow: 256000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "kimi-k2-thinking",
    name: "Kimi K2 Thinking",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.6,
      output: 2.5,
      cacheRead: 0.15,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "kimi-k2-thinking-turbo",
    name: "Kimi K2 Thinking Turbo",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 1.15,
      output: 8,
      cacheRead: 0.15,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "kimi-k2.5",
    name: "Kimi K2.5",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.6,
      output: 3,
      cacheRead: 0.09999999999999999,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "kimi-k2.6",
    name: "Kimi K2.6",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.95,
      output: 4,
      cacheRead: 0.16,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "kimi-k2.7-code",
    name: "Kimi K2.7 Code",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.95,
      output: 4,
      cacheRead: 0.19,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "kimi-k2.7-code-highspeed",
    name: "Kimi K2.7 Code Highspeed",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 1.9,
      output: 8,
      cacheRead: 0.38,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "qwen-max",
    name: "Qwen Max",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 1.5999999999999999,
      output: 6.3999999999999995,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 32768,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen-max-latest",
    name: "Qwen Max Latest",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 1.5999999999999999,
      output: 6.3999999999999995,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 32768,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen-plus",
    name: "Qwen Plus",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.39999999999999997,
      output: 1.2,
      cacheRead: 0.08,
      cacheWrite: 0.5,
    },
    contextWindow: 131072,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen-plus-latest",
    name: "Qwen Plus Latest",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.39999999999999997,
      output: 1.2,
      cacheRead: 0.08,
      cacheWrite: 0.5,
    },
    contextWindow: 1000000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen-flash",
    name: "Qwen Flash",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.049999999999999996,
      output: 0.39999999999999997,
      cacheRead: 0.01,
      cacheWrite: 0.0625,
    },
    contextWindow: 1000000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen-omni-turbo",
    name: "Qwen Omni Turbo",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.19999999999999998,
      output: 0.7999999999999999,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 32768,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen3-coder-plus",
    name: "Qwen3 Coder Plus",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 6,
      output: 60,
      cacheRead: 1.2,
      cacheWrite: 7.5,
    },
    contextWindow: 1000000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen3-235b-a22b-instruct-2507",
    name: "Qwen3 235B A22B Instruct 2507",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.19999999999999998,
      output: 0.6,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 262000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen3-235b-a22b-thinking-2507",
    name: "Qwen3 235B A22B Thinking 2507",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.19999999999999998,
      output: 0.6,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 262000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "qwen3-235b-a22b-fp8",
    name: "Qwen3 235B A22B FP8",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.19999999999999998,
      output: 0.7999999999999999,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 40960,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen3.5-9b",
    name: "Qwen3.5 9B",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.09999999999999999,
      output: 0.15,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "qwen3-32b",
    name: "Qwen3 32B",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.09999999999999999,
      output: 0.3,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 32768,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen2-5-vl-72b-instruct",
    name: "Qwen2.5 VL 72B Instruct",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.13,
      output: 0.39999999999999997,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 32768,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen3-vl-8b-instruct",
    name: "Qwen3 VL 8B Instruct",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.08,
      output: 0.5,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 131072,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen3-coder-480b-a35b-instruct",
    name: "Qwen3 Coder 480B A35B Instruct",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.39999999999999997,
      output: 1.7999999999999998,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen3-coder-30b-a3b-instruct",
    name: "Qwen3 Coder 30B A3B Instruct",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.09999999999999999,
      output: 0.3,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 262000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen3-30b-a3b-instruct-2507",
    name: "Qwen3 30B A3B Instruct 2507",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.09999999999999999,
      output: 0.3,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 262000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen3-next-80b-a3b-thinking",
    name: "Qwen3 Next 80B A3B Thinking",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.5,
      output: 6,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 131072,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "qwen3-next-80b-a3b-instruct",
    name: "Qwen3 Next 80B A3B Instruct",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.5,
      output: 2,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 131072,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen3-max",
    name: "Qwen3 Max",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 3,
      output: 15,
      cacheRead: 0.6,
      cacheWrite: 3.75,
    },
    contextWindow: 262144,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "qwen3.7-max",
    name: "Qwen3.7 Max",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 2.5,
      output: 7.5,
      cacheRead: 0.5,
      cacheWrite: 3.125,
    },
    contextWindow: 1000000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "qwen3.7-plus",
    name: "Qwen3.7 Plus",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.39999999999999997,
      output: 1.5999999999999999,
      cacheRead: 0.08,
      cacheWrite: 0.5,
    },
    contextWindow: 1000000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "qwen3-coder-next",
    name: "Qwen3 Coder Next",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.108,
      output: 0.675,
      cacheRead: 0.06,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen3-vl-30b-a3b-instruct",
    name: "Qwen3 VL 30B A3B Instruct",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.19999999999999998,
      output: 0.7,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 131072,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen3-vl-30b-a3b-thinking",
    name: "Qwen3 VL 30B A3B Thinking",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.19999999999999998,
      output: 1,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 131072,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "qwen3-4b-fp8",
    name: "Qwen3 4B FP8",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.03,
      output: 0.03,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen35-397b-a17b",
    name: "Qwen3.5 397B A17B",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.6,
      output: 3.5999999999999996,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "qwen-image-plus",
    name: "Qwen Image Plus",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 2000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen-image-max",
    name: "Qwen Image Max",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 2000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen-image",
    name: "Qwen Image",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 2000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen-image-max-2025-12-30",
    name: "Qwen Image Max 2025-12-30",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 2000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen-coder-plus",
    name: "Qwen Coder Plus",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.502,
      output: 1.004,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 131072,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen3-coder-flash",
    name: "Qwen3 Coder Flash",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.3,
      output: 1.5,
      cacheRead: 0.06,
      cacheWrite: 0.375,
    },
    contextWindow: 1000000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen3-vl-plus",
    name: "Qwen3 VL Plus",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.19999999999999998,
      output: 1.5999999999999999,
      cacheRead: 0.04,
      cacheWrite: 0.25,
    },
    contextWindow: 262144,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen3-vl-flash",
    name: "Qwen3 VL Flash",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.049999999999999996,
      output: 0.39999999999999997,
      cacheRead: 0.01,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen3-vl-235b-a22b-instruct",
    name: "Qwen3 VL 235B A22B Instruct",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.5,
      output: 2,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 131072,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen3-vl-235b-a22b-thinking",
    name: "Qwen3 VL 235B A22B Thinking",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.5,
      output: 2,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 131072,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "qwen2-5-vl-32b-instruct",
    name: "Qwen2.5 VL 32B Instruct",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 1.4,
      output: 4.199999999999999,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 131072,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen-image-edit-plus",
    name: "Qwen Image Edit Plus",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 2000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen-image-edit-max",
    name: "Qwen Image Edit Max",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 2000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "qwen3.6-max-preview",
    name: "Qwen3.6 Max Preview",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 1.3,
      output: 7.8,
      cacheRead: 0.13,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "qwen3.6-plus",
    name: "Qwen3.6 Plus",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.5,
      output: 3,
      cacheRead: 0.049999999999999996,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "qwen3.6-35b-a3b",
    name: "Qwen3.6 35B A3B",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.248,
      output: 1.4849999999999999,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "seed-1-6-250615",
    name: "Seed 1.6 (250615)",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.25,
      output: 2,
      cacheRead: 0.049999999999999996,
      cacheWrite: 0,
    },
    contextWindow: 256000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "seed-1-6-250915",
    name: "Seed 1.6 (250915)",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.25,
      output: 2,
      cacheRead: 0.049999999999999996,
      cacheWrite: 0,
    },
    contextWindow: 256000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "seed-1-6-flash-250715",
    name: "Seed 1.6 Flash (250715)",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.07,
      output: 0.3,
      cacheRead: 0.015,
      cacheWrite: 0,
    },
    contextWindow: 256000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "seed-1-8-251228",
    name: "Seed 1.8 (251228)",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.25,
      output: 2,
      cacheRead: 0.049999999999999996,
      cacheWrite: 0,
    },
    contextWindow: 256000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "seedream-4-0",
    name: "Seedream 4.0",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 2000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "seedream-4-5",
    name: "Seedream 4.5",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 2000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "fugu-ultra",
    name: "Fugu Ultra",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 5,
      output: 30,
      cacheRead: 0.5,
      cacheWrite: 0,
    },
    contextWindow: 1000000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "nemotron-3-ultra-550b",
    name: "Nemotron 3 Ultra 550B",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.5,
      output: 2.5,
      cacheRead: 0.15,
      cacheWrite: 0,
    },
    contextWindow: 262144,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "glm-5.2",
    name: "GLM-5.2",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 1.4,
      output: 4.4,
      cacheRead: 0.26,
      cacheWrite: 0,
    },
    contextWindow: 1000000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "glm-5.1",
    name: "GLM-5.1",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 1.4,
      output: 4.4,
      cacheRead: 0.26,
      cacheWrite: 0,
    },
    contextWindow: 204800,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "glm-5",
    name: "GLM-5",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 1,
      output: 3.1999999999999997,
      cacheRead: 0.19999999999999998,
      cacheWrite: 0,
    },
    contextWindow: 203000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "glm-4.5",
    name: "GLM-4.5",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.6,
      output: 2.2,
      cacheRead: 0.11,
      cacheWrite: 0,
    },
    contextWindow: 131000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "glm-4.5v",
    name: "GLM-4.5V",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.6,
      output: 1.7999999999999998,
      cacheRead: 0.11,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "glm-4.5-air",
    name: "GLM-4.5 Air",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.19999999999999998,
      output: 1.1,
      cacheRead: 0.03,
      cacheWrite: 0,
    },
    contextWindow: 131000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "glm-4.5-x",
    name: "GLM-4.5 X",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 2.2,
      output: 8.9,
      cacheRead: 0.44999999999999996,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "glm-4.5-airx",
    name: "GLM-4.5 AirX",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 1.1,
      output: 4.5,
      cacheRead: 0.22,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "glm-4.5-flash",
    name: "GLM-4.5 Flash",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "glm-4.7",
    name: "GLM-4.7",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.6,
      output: 2.2,
      cacheRead: 0.11,
      cacheWrite: 0,
    },
    contextWindow: 204800,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "glm-4.7-flashx",
    name: "GLM-4.7 FlashX",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.07,
      output: 0.39999999999999997,
      cacheRead: 0.01,
      cacheWrite: 0,
    },
    contextWindow: 200000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "glm-4.7-flash-free",
    name: "GLM-4.7 Flash (Free)",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 200000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "glm-4.7-flash",
    name: "GLM-4.7 Flash",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.06,
      output: 0.39999999999999997,
      cacheRead: 0.01,
      cacheWrite: 0,
    },
    contextWindow: 200000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "glm-4.6",
    name: "GLM-4.6",
    reasoning: true,
    input: ["text"],
    cost: {
      input: 0.6,
      output: 2.2,
      cacheRead: 0.11,
      cacheWrite: 0,
    },
    contextWindow: 204800,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "glm-4-32b-0414-128k",
    name: "GLM-4 32B (0414-128k)",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0.09999999999999999,
      output: 0.09999999999999999,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "glm-4.6v",
    name: "GLM-4.6V",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.3,
      output: 0.8999999999999999,
      cacheRead: 0.049999999999999996,
      cacheWrite: 0,
    },
    contextWindow: 131072,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "glm-4.6v-flashx",
    name: "GLM-4.6V FlashX",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0.04,
      output: 0.39999999999999997,
      cacheRead: 0.004,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "glm-4.6v-flash",
    name: "GLM-4.6V Flash",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
    thinkingLevelMap: {
      minimal: null,
      low: null,
      medium: "medium",
      high: "high",
      xhigh: "xhigh",
    },
  },
  {
    id: "cogview-4",
    name: "CogView-4",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 2000,
    maxTokens: 16384,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
  {
    id: "glm-image",
    name: "GLM-Image",
    reasoning: false,
    input: ["text"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 2000,
    maxTokens: 32768,
    compat: {
      supportsDeveloperRole: false,
      maxTokensField: "max_tokens",
    },
  },
];
